import base64
import re

fn = "D:/work/new_pipeline/plugins/medical_plugin.py"
c = open(fn, "rb").read()

# Find method boundaries
i = c.find(b"medical_write_quarter")
s = c.rfind(b"@staticmethod", 0, i)
e = len(c)

# Build new method
lines = []
lines.append(b"    @staticmethod")
lines.append(b"    def medical_write_quarter(context, params):")
lines.append(b'        """')
lines.append("根据date_row中的月度数据自动判断所属季度，在quarter_row中合并单元格并写入yyyyQn".encode("utf-8"))
lines.append(b"")
lines.append("参数:".encode("utf-8"))
lines.append("    quarter_row: 季度信息写入行号 (默认2)".encode("utf-8"))
lines.append("    date_row: 月度日期所在行号 (默认3)".encode("utf-8"))
lines.append("    data_start_column: 数据起始列号 (默认2)".encode("utf-8"))
lines.append(b'        """')
lines.append(b'        ws = context["ws"]')
lines.append(b'        quarter_row = params.get("quarter_row", 2)')
lines.append(b'        date_row = params.get("date_row", 3)')
lines.append(b'        data_start_column = params.get("data_start_column", 2)')
lines.append(b"")
lines.append(b"        # 1. scan date_row for all headers, parse to (col, year, month)")
lines.append(b"        periods = []")
lines.append(b"        col = data_start_column")
lines.append(b"        while True:")
lines.append(b"            cell_value = ws.cell(row=date_row, column=col).value")
lines.append(b"            if cell_value is None:")
lines.append(b"                break")
lines.append(b"            parsed = MedicalPlugin._parse_period(str(cell_value))")
lines.append(b"            if parsed:")
lines.append(b"                periods.append((col, parsed[0], parsed[1]))")
lines.append(b"            col += 1")
lines.append(b"")
lines.append(b"        if not periods:")
lines.append(("            print(" + chr(39) + "    - date_row" + chr(20013) + "未找到日期数据，跳过季度写入" + chr(39) + ")").encode("utf-8"))
lines.append(b"            return")
lines.append(b"")
lines.append(b"        # 2. group consecutive same-quarter months")
lines.append(b"        quarter_groups = []")
lines.append(b"        current_group = None")
lines.append(b"")
lines.append(b"        for period_col, year, month in periods:")
lines.append(b"            q = (month - 1) // 3 + 1")
lines.append(b"            if (current_group is None")
lines.append(b"                    or current_group[0] != year")
lines.append(b"                    or current_group[1] != q")
lines.append(b"                    or period_col != current_group[3] + 1):")
lines.append(b"                if current_group is not None:")
lines.append(b"                    quarter_groups.append(current_group)")
lines.append(b'                current_group = [year, q, period_col, period_col]')
lines.append(b"            else:")
lines.append(b"                current_group[3] = period_col")
lines.append(b"")
lines.append(b"        if current_group is not None:")
lines.append(b"            quarter_groups.append(current_group)")
lines.append(b"")
lines.append(b"        # 3. unmerge quarter_row, write quarters")
lines.append(b"        MedicalPlugin._unmerge_row(ws, quarter_row)")
lines.append(b"        for year, q, start_col, end_col in quarter_groups:")
lines.append(b'            cell = ws.cell(row=quarter_row, column=start_col)')
lines.append(b'            cell.value = f"{year}Q{q}"')
lines.append(b"            if start_col != end_col:")
lines.append(b"                ws.merge_cells(")
lines.append(b"                    start_row=quarter_row, start_column=start_col,")
lines.append(b"                    end_row=quarter_row, end_column=end_col")
lines.append(b"                )")
lines.append(b"")
lines.append((chr(39) + "    - " + chr(23436) + chr(25104) + chr(23383) + chr(24230) + chr(20889) + chr(20870) + chr(20889) + ": " + chr(20849) + chr(37) + chr(100) + chr(20010) + chr(23383) + chr(24230) + chr(39) + chr(32) + chr(37) + chr(32) + chr(108) + chr(101) + chr(110) + chr(40) + chr(113) + chr(117) + chr(97) + chr(114) + chr(116) + chr(101) + chr(114) + chr(95) + chr(103) + chr(114) + chr(111) + chr(117) + chr(112) + chr(115) + chr(41)).encode("utf-8"))

new_method = b"\n".join(lines)

# Patch the file
result = c[:s] + new_method
open(fn, "wb").write(result)
print("Patched successfully. New file size:", len(result))
