def get_method():
    L = []
    L.append("    @staticmethod")
    L.append("    def medical_write_quarter(context, params):")
    L.append('        """')
    L.append('        根据date_row中的月度数据自动判断所属季度，在quarter_row中合并单元格并写入yyyyQn')
    L.append('')
    L.append('        参数:')
    L.append('            quarter_row: 季度信息写入行号 (默认2)')
    L.append('            date_row: 月度日期所在行号 (默认3)')
    L.append('            data_start_column: 数据起始列号 (默认2)')
    L.append('        """')
    L.append('        ws = context["ws"]')
    L.append('        quarter_row = params.get("quarter_row", 2)')
    L.append('        date_row = params.get("date_row", 3)')
    L.append('        data_start_column = params.get("data_start_column", 2)')
    L.append('')
    L.append('        # 1. 扫描 date_row，读取所有列头并解析为 (col, year, month)')
    L.append('        periods = []')
    L.append('        col = data_start_column')
    L.append('        while True:')
    L.append('            cell_value = ws.cell(row=date_row, column=col).value')
    L.append('            if cell_value is None:')
    L.append('                break')
    L.append('            parsed = MedicalPlugin._parse_period(str(cell_value))')
    L.append('            if parsed:')
    L.append('                periods.append((col, parsed[0], parsed[1]))')
    L.append('            col += 1')
    L.append('')
    L.append('        if not periods:')
    L.append('            print("    - date_row 中未找到日期数据，跳过季度写入")')
    L.append('            return')
    L.append('')
    L.append('        # 2. 将连续的同一季度月份分组')
    L.append('        quarter_groups = []')
    L.append('        current_group = None')
    L.append('')
    L.append('        for period_col, year, month in periods:')
    L.append('            q = (month - 1) // 3 + 1')
    L.append('            if (current_group is None')
    L.append('                    or current_group[0] != year')
    L.append('                    or current_group[1] != q')
    L.append('                    or period_col != current_group[3] + 1):')
    L.append('                if current_group is not None:')
    L.append('                    quarter_groups.append(current_group)')
    L.append('                current_group = [year, q, period_col, period_col]')
    L.append('            else:')
    L.append('                current_group[3] = period_col')
    L.append('')
    L.append('        if current_group is not None:')
    L.append('            quarter_groups.append(current_group)')
    L.append('')
    L.append('        # 3. 解除 quarter_row 合并，写入季度')
    L.append('        MedicalPlugin._unmerge_row(ws, quarter_row)')
    L.append('        for year, q, start_col, end_col in quarter_groups:')
    L.append('            cell = ws.cell(row=quarter_row, column=start_col)')
    L.append('            cell.value = f"{year}Q{q}"')
    L.append('            if start_col != end_col:')
    L.append('                ws.merge_cells(')
    L.append('                    start_row=quarter_row, start_column=start_col,')
    L.append('                    end_row=quarter_row, end_column=end_col')
    L.append('                )')
    L.append('        print(f"    - 完成季度行写入: 共 {len(quarter_groups)} 个季度")')
    return L
